
whodunit: whodunit.c
		gcc whodunit.c -o whodunit -ggdb -Wall

resize: resize.c
		gcc resize.c -o resize -ggdb -Wall

copy: copy.c
		gcc copy.c -o copy -ggdb -Wall

info: info.c
		gcc info.c -o info -Wall

clean:
		rm -f a.out *.o copy resize info whodunit
